server {
    listen 80;
    server_name localhost;

    # 1. Sirve la página web de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Redirige a Ventas respetando la ruta exacta de Spring Boot
    location /api/v1/ventas {
        proxy_pass http://backend-venta-svc:8080; # <- Nombre del Service interno
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Redirige a Despachos respetando la ruta exacta de Spring Boot
    location /api/v1/despachos {
        proxy_pass http://backend-despacho-svc:8080; # <- Nombre del Service interno
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
